# Generated by Django 6.0.4 on 2026-06-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], default='viewer', max_length=20),
        ),
    ]
