# Generated by Django 6.0.4 on 2026-05-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peringkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peringkat', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Peringkat',
                'ordering': ['peringkat'],
            },
        ),
        migrations.CreateModel(
            name='SektorUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sektor Usaha',
                'ordering': ['sektor'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='JenisUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
                ('sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis_usaha', to='atribut.sektorusaha')),
            ],
            options={
                'verbose_name_plural': 'Jenis Usaha',
                'ordering': ['jenis'],
                'unique_together': {('sektor', 'jenis')},
            },
        ),
    ]
