# Generated by Django 6.0.4 on 2026-05-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atribut', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sektorusaha',
            options={'ordering': ['sektor'], 'verbose_name_plural': 'sektor_usaha'},
        ),
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
