# Generated by Django 6.0.4 on 2026-05-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atribut', '0002_alter_sektorusaha_options_status_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
    ]
