# Generated by Django 6.0.4 on 2026-05-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atribut', '0001_initial'),
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bumdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bumdes', models.CharField(max_length=150)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bumdes', to='wilayah.desa')),
                ('jenis_usaha', models.ManyToManyField(blank=True, related_name='bumdes_jenis', to='atribut.jenisusaha')),
                ('peringkat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bumdes_peringkat', to='atribut.peringkat')),
                ('sektor_usaha', models.ManyToManyField(blank=True, related_name='bumdes_sektor', to='atribut.sektorusaha')),
                ('status_bumdes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bumdes_status', to='atribut.status')),
            ],
            options={
                'verbose_name_plural': 'BUMDes',
                'ordering': ['nama_bumdes'],
            },
        ),
        migrations.CreateModel(
            name='Legalitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_perdes', models.CharField(max_length=100)),
                ('tanggal_perdes', models.DateField(blank=True, null=True)),
                ('nomor_ahu', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_ahu', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bumdes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legalitas', to='bumdes.bumdes')),
            ],
            options={
                'verbose_name_plural': 'Legalitas',
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penasihat', models.CharField(max_length=100)),
                ('no_penasihat', models.CharField(max_length=20)),
                ('pengawas', models.CharField(max_length=100)),
                ('no_pengawas', models.CharField(max_length=20)),
                ('direktur', models.CharField(max_length=100)),
                ('no_direktur', models.CharField(max_length=20)),
                ('sekretaris', models.CharField(max_length=100)),
                ('no_sekretaris', models.CharField(max_length=20)),
                ('bendahara', models.CharField(max_length=100)),
                ('no_bendahara', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bumdes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petugas', to='bumdes.bumdes')),
            ],
            options={
                'verbose_name_plural': 'Petugas',
            },
        ),
    ]
