# Generated by Django 6.0.4 on 2026-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumdes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugas',
            name='bendahara',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='direktur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='no_bendahara',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='no_direktur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='no_penasihat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='no_pengawas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='no_sekretaris',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='penasihat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='pengawas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='sekretaris',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
