# Generated by Django 6.0.4 on 2026-05-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumdes', '0002_alter_petugas_bendahara_alter_petugas_direktur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalitas',
            name='nomor_perdes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
